<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-19T13:18:55 IST" name="Default suite" finished-at="2024-10-19T13:18:56 IST" duration-ms="51">
    <groups>
    </groups>
    <test started-at="2024-10-19T13:18:55 IST" name="Default test" finished-at="2024-10-19T13:18:56 IST" duration-ms="51">
      <class name="listenerPractice.TestClass">
        <test-method is-config="true" signature="suiteConfig()[pri:0, instance:listenerPractice.TestClass@7b9a4292]" started-at="2024-10-19T13:18:55 IST" name="suiteConfig" finished-at="2024-10-19T13:18:55 IST" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suiteConfig -->
        <test-method is-config="true" signature="testConfig()[pri:0, instance:listenerPractice.TestClass@7b9a4292]" started-at="2024-10-19T13:18:55 IST" name="testConfig" finished-at="2024-10-19T13:18:55 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testConfig -->
        <test-method is-config="true" signature="classConfig()[pri:0, instance:listenerPractice.TestClass@7b9a4292]" started-at="2024-10-19T13:18:56 IST" name="classConfig" finished-at="2024-10-19T13:18:56 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classConfig -->
        <test-method is-config="true" signature="methodConfig()[pri:0, instance:listenerPractice.TestClass@7b9a4292]" started-at="2024-10-19T13:18:56 IST" name="methodConfig" finished-at="2024-10-19T13:18:56 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodConfig -->
        <test-method signature="demo2()[pri:0, instance:listenerPractice.TestClass@7b9a4292]" started-at="2024-10-19T13:18:56 IST" name="demo2" finished-at="2024-10-19T13:18:56 IST" duration-ms="7" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at listenerPractice.TestClass.demo2(TestClass.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demo2 -->
        <test-method is-config="true" signature="methodTeardown()[pri:0, instance:listenerPractice.TestClass@7b9a4292]" started-at="2024-10-19T13:18:56 IST" name="methodTeardown" finished-at="2024-10-19T13:18:56 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodTeardown -->
        <test-method signature="demo1()[pri:0, instance:listenerPractice.TestClass@7b9a4292]" started-at="2024-10-19T13:18:56 IST" name="demo1" finished-at="2024-10-19T13:18:56 IST" depends-on-methods="listenerPractice.TestClass.demo2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestClass.demo1()[pri:0, instance:listenerPractice.TestClass@7b9a4292] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestClass.demo1()[pri:0, instance:listenerPractice.TestClass@7b9a4292] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demo1 -->
        <test-method is-config="true" signature="classTeardown()[pri:0, instance:listenerPractice.TestClass@7b9a4292]" started-at="2024-10-19T13:18:56 IST" name="classTeardown" finished-at="2024-10-19T13:18:56 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classTeardown -->
        <test-method is-config="true" signature="testTeardown()[pri:0, instance:listenerPractice.TestClass@7b9a4292]" started-at="2024-10-19T13:18:56 IST" name="testTeardown" finished-at="2024-10-19T13:18:56 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTeardown -->
        <test-method is-config="true" signature="suiteTeardown()[pri:0, instance:listenerPractice.TestClass@7b9a4292]" started-at="2024-10-19T13:18:56 IST" name="suiteTeardown" finished-at="2024-10-19T13:18:56 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suiteTeardown -->
      </class> <!-- listenerPractice.TestClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
